default_language_version:
  python: python3.8

repos:
- repo: https://github.com/psf/black
  rev: 19.10b0
  hooks:
  - id: black
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.8.3
  hooks:
  - id: flake8
    additional_dependencies: [flake8-comprehensions>=3.2.3, flake8-bugbear>=20.1.4]
- repo: https://github.com/pre-commit/mirrors-isort
  rev: v5.2.1
  hooks:
  - id: isort
