name: tweetcloud
channels:
  - conda-forge
dependencies:
  - python=3.8.*
  - coloredlogs=14.*
  - matplotlib=3.3.*
  - pandas=1.1.*
  - pillow=7.2.*
  - python-twitter=3.*
  - wordcloud=1.7.*

  # dev dependencies
  - black=19.*
  - flake8=3.8.*
  - isort=5.2.*
  - pre-commit=2.6.*
  - pytest=6.0.*
